fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
  symlinks:
    puppet: "#{source_dir}"
